# Generated by Django 4.0.6 on 2022-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='UID')),
                ('cpu', models.PositiveSmallIntegerField(verbose_name='CPU cores count')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM volume')),
                ('hdd', models.PositiveIntegerField(verbose_name='HDD volume')),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('blocked', 'BLOCKED'), ('stopped', 'STOPPED')], default='stopped', max_length=7, verbose_name='VPS status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'vps object',
                'verbose_name_plural': 'vps objects',
                'db_table': 'vps',
                'ordering': ('-created_at',),
            },
        ),
    ]
